fix(core/exporter): Fix dtype mismatch in latest pandas
TypeError: Invalid value '18' for dtype 'str'. Value should be a string or missing value, got 'int' instead.